### ISSUE TITLE
Please add support for delegation

### ISSUE THREAD

**Issue by woutervb** [alchemy-charmers/charm-matrix#1]
As described on https://github.com/matrix-org/synapse/blob/master/docs/delegate.md it is possible to have the server hosted on a different domain name, then the domain the user accounts have.

E.g. the server_name is then set to example.com while the host itself has matrix.example.com as it's fqdn.

This will require that the webserver hosting example.com has the proper `.well-known/server/matrix` file setup, but that is something that this charm cannot realize (unless the reverse proxy happens to be the same)

**Comment by devec0** [comment]
With the 8448 port listening, and the ability to specify external name and server name separately, this is now possible.
